add static class
razorpay/razorpay-java pull request #146
Opened 2022-01-27 08:55 UTC by ankitdas13

2022-01-28 08:17 UTC, ersinghlovepreet commented on src/main/java/com/razorpay/ApiClient.java
> +    	   String cls = StaticEntity(response);
StaticEntity method should be populateEntiryFromURL(response.request().url().pathSegments())

2022-01-28 08:20 UTC, ersinghlovepreet commented on src/main/java/com/razorpay/StaticClass.java
> +public class StaticClass {
This should be enum with URL name mapping

2022-02-07 06:02 UTC, ersinghlovepreet requested changes

2022-02-07 06:02 UTC, ersinghlovepreet commented on src/main/java/com/razorpay/ApiClient.java
> +          responseJson.put("entity",entityName);
"entity" -> ENTITY

2022-02-07 06:12 UTC, ankitdas13 commented on src/main/java/com/razorpay/ApiClient.java
> +          responseJson.put("entity",entityName);
i have changed this to `Entity`

2022-02-07 08:51 UTC, ersinghlovepreet approved these changes

2022-03-07 16:09 UTC, merged